title: Add alt text to images
hero_image: images/banner.png
description: Add alt text to images.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Add alt text to images
