title: Alt-tekst toevoegen aan afbeeldingen
hero_image: images/banner.png
description: Alt-tekst toevoegen aan afbeeldingen.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Alt-tekst toevoegen aan afbeeldingen
