title: Ajouter un texte alternatif aux images
hero_image: images/banner.png
description: Ajoute un texte alternatif aux images.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Ajouter un texte alternatif aux images
